version: '3.8'

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/Users/rezayoga/VisualStudioCodeProjects/flask-tdd-docker/project
    ports:
      - 5004:5000
    environment:
      - FLASK_APP=src/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=src.config.DevelopmentConfig
      - DATABASE_URL=postgresql://postgres:postgres@api-db:5432/api_dev  # new
      - DATABASE_TEST_URL=postgresql://postgres:postgres@api-db:5432/api_test  # new
    depends_on:  # new
      - api-db

  api-db:  # new
    build:
      context: ./src/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres